// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	agree "quora/app/action/cmd/api/internal/handler/agree"
	collection "quora/app/action/cmd/api/internal/handler/collection"
	follow "quora/app/action/cmd/api/internal/handler/follow"
	like "quora/app/action/cmd/api/internal/handler/like"
	"quora/app/action/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/action/agree",
				Handler: agree.AgreeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/action/Like",
				Handler: like.LikeHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/action/collection",
				Handler: collection.CollectionHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/action/follow",
				Handler: follow.FollowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
