// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Uid      int64  `json:"uid"`
	UserName string `json:"user_name"`
	Avatar   string `json:"avatar"`
	Gender   int    `json:"gender"`
}

type ChildComments struct {
	Id           int64  `json:"id"`
	Content      string `json:"content"`
	Likes        int64  `json:"likes"`
	ResourceType string `json:"resource_type"`
	User         User   `json:"user"`
	ReplyUser    User   `json:"reply_user"`
	CreateAt     int64  `json:"create_at"`
	IP           string `json:"ip"`
}

type Comment struct {
	Id                int64           `json:"id"`
	ResourceType      string          `json:"resource_type"` //Answer Artical
	User              User            `json:"user"`
	Content           string          `json:"content"`
	Likes             int64           `json:"likes"`
	ChildCommentCount int64           `json:"child_comment_count"`
	ChildComments     []ChildComments `json:"childcomments"`
	CreateAt          int64           `json:"create_at"`
}

type CommentStatus struct {
	Status  int64  `json:"status"`
	Message string `json:"message"`
}

type PostCommentReq struct {
	Uid          int64  `form:"uid" json:"uid"`
	ResourceType string `form:"resource_type" json:"resource_type"`
	Type         string `form:"type" json:"type"`
	IP           string `form:"ip" json:"ip"`
	Pid          int64  `form:"pid" json:"pid"`
	Content      string `form:"content" json:"content"`
	CreateAt     int64  `form:"create_at" json:"create_at"`
}

type PostCommentResp struct {
	Data PostCommentReq `json:"data"`
	Id   int64          `json:"id"`
}

type DeleteCommmentReq struct {
	Id   int64  `form:"id"`
	Type string `form:"type"`
}

type DeleteCommmentResp struct {
	Message string `json:"message"`
	Status  int    `json:"status"`
}

type GetCommentReq struct {
	Pid int64 `json:"pid"`
}

type GetCommentResp struct {
	CommentStatus CommentStatus `json:"comment_status"`
	Data          []Comment     `json:"data"`
}

type GetChildCommentReq struct {
	Pid int64 `form:"pid"`
}

type GetChildCommentResp struct {
	Data []ChildComments `json:"data"`
}

type PostChildCommentReq struct {
	Pid      int64  `form:"pid" json:"pid"`
	Uid      int64  `form:"uid" json:"uid"`
	Content  string `form:"content" json:"content"`
	CreateAt int64  `form:"create_at" json:"create_at"`
	Repy_uid int64  `form:"repy_uid" json:"repy_uid"`
	Repy_cid int64  `form:"repy_cid" json:"repy_cid"`
}

type PostChlidCommentResp struct {
	Data PostChildCommentReq `json:"data"`
	Id   int64               `json:"id"`
}
