// Code generated by goctl. DO NOT EDIT.
package types

type AgreeReq struct {
	Pid    int64  `form:"pid"`
	Object string `form:"object"`
	Puid   int64  `form:"puid"`
	Opt    int64  `form:"opt"`
}

type AgreeResq struct {
	Message string `json:"message"`
	Status  int64  `json:"status"`
}

type LikeReq struct {
	Pid    int64  `form:"pid"`
	Object string `form:"object"`
	PUid   int64  `form:"puid"`
}

type LikeResp struct {
	Message string `json:"message"`
	Status  int64  `json:"status"`
}

type CollectionReq struct {
	Pid    int64  `form:"pid"`
	PUid   int64  `form:"puid"`
	Object string `form:"object"`
}

type CollectionResp struct {
	Message string `josn:"message"`
	Status  int64  `josn:"status"`
}

type FollowReq struct {
	Pid    int64  `form:"pid"`
	Object string `form:"object"`
}

type FollowResp struct {
	Message string `form:"message"`
	Status  int64  `form:"status"`
}

type User struct {
	Id       int64  `json:"id"`
	UserName string `json:"userName"`
	Avatar   string `json:"avatar"`
}
