// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	answer "quora/app/qa/cmd/api/internal/handler/answer"
	question "quora/app/qa/cmd/api/internal/handler/question"
	"quora/app/qa/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/question/post",
					Handler: question.PostQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/question/update",
					Handler: question.UpdateQuestionHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/question/delete",
					Handler: question.DeleteQuestionHandler(serverCtx),
				},
			}...,
		),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/question/:id",
				Handler: question.GetQuestionHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Auth},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/answer/post",
					Handler: answer.PostAnswerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/answer/update",
					Handler: answer.UpdateAnswerHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/answer/delete",
					Handler: answer.DeleteAnswerHandler(serverCtx),
				},
			}...,
		),
	)
}
