// Code generated by goctl. DO NOT EDIT!
// Source: qa.proto

package server

import (
	"context"

	"quora/app/qa/cmd/rpc/internal/logic"
	"quora/app/qa/cmd/rpc/internal/svc"
	"quora/app/qa/cmd/rpc/pb"
)

type QaServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedQaServer
}

func NewQaServer(svcCtx *svc.ServiceContext) *QaServer {
	return &QaServer{
		svcCtx: svcCtx,
	}
}

// -----------------------answer-----------------------
func (s *QaServer) AddAnswer(ctx context.Context, in *pb.AddAnswerReq) (*pb.AddAnswerResp, error) {
	l := logic.NewAddAnswerLogic(ctx, s.svcCtx)
	return l.AddAnswer(in)
}

func (s *QaServer) UpdateAnswer(ctx context.Context, in *pb.UpdateAnswerReq) (*pb.UpdateAnswerResp, error) {
	l := logic.NewUpdateAnswerLogic(ctx, s.svcCtx)
	return l.UpdateAnswer(in)
}

func (s *QaServer) DelAnswer(ctx context.Context, in *pb.DelAnswerReq) (*pb.DelAnswerResp, error) {
	l := logic.NewDelAnswerLogic(ctx, s.svcCtx)
	return l.DelAnswer(in)
}

func (s *QaServer) GetAnswerById(ctx context.Context, in *pb.GetAnswerByIdReq) (*pb.GetAnswerByIdResp, error) {
	l := logic.NewGetAnswerByIdLogic(ctx, s.svcCtx)
	return l.GetAnswerById(in)
}

func (s *QaServer) SearchAnswer(ctx context.Context, in *pb.SearchAnswerReq) (*pb.SearchAnswerResp, error) {
	l := logic.NewSearchAnswerLogic(ctx, s.svcCtx)
	return l.SearchAnswer(in)
}

func (s *QaServer) GetAnswerListByQid(ctx context.Context, in *pb.GetAnswerListByPidReq) (*pb.GetAnswerListByPidResp, error) {
	l := logic.NewGetAnswerListByQidLogic(ctx, s.svcCtx)
	return l.GetAnswerListByQid(in)
}

func (s *QaServer) GetAnswerListByUid(ctx context.Context, in *pb.GetAnswerListByUidReq) (*pb.GetAnswerListByUidResp, error) {
	l := logic.NewGetAnswerListByUidLogic(ctx, s.svcCtx)
	return l.GetAnswerListByUid(in)
}

// -----------------------question-----------------------
func (s *QaServer) AddQuestion(ctx context.Context, in *pb.AddQuestionReq) (*pb.AddQuestionResp, error) {
	l := logic.NewAddQuestionLogic(ctx, s.svcCtx)
	return l.AddQuestion(in)
}

func (s *QaServer) UpdateQuestion(ctx context.Context, in *pb.UpdateQuestionReq) (*pb.UpdateQuestionResp, error) {
	l := logic.NewUpdateQuestionLogic(ctx, s.svcCtx)
	return l.UpdateQuestion(in)
}

func (s *QaServer) DelQuestion(ctx context.Context, in *pb.DelQuestionReq) (*pb.DelQuestionResp, error) {
	l := logic.NewDelQuestionLogic(ctx, s.svcCtx)
	return l.DelQuestion(in)
}

func (s *QaServer) GetQuestionById(ctx context.Context, in *pb.GetQuestionByIdReq) (*pb.GetQuestionByIdResp, error) {
	l := logic.NewGetQuestionByIdLogic(ctx, s.svcCtx)
	return l.GetQuestionById(in)
}

func (s *QaServer) SearchQuestion(ctx context.Context, in *pb.SearchQuestionReq) (*pb.SearchQuestionResp, error) {
	l := logic.NewSearchQuestionLogic(ctx, s.svcCtx)
	return l.SearchQuestion(in)
}
