// Code generated by goctl. DO NOT EDIT!
// Source: comment.proto

package server

import (
	"context"

	"quora/app/comment/cmd/rpc/internal/logic"
	"quora/app/comment/cmd/rpc/internal/svc"
	"quora/app/comment/cmd/rpc/pb"
)

type CommentServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCommentServer
}

func NewCommentServer(svcCtx *svc.ServiceContext) *CommentServer {
	return &CommentServer{
		svcCtx: svcCtx,
	}
}

func (s *CommentServer) AddChildComment(ctx context.Context, in *pb.AddChildCommentReq) (*pb.AddChildCommentResp, error) {
	l := logic.NewAddChildCommentLogic(ctx, s.svcCtx)
	return l.AddChildComment(in)
}

func (s *CommentServer) UpdateChildComment(ctx context.Context, in *pb.UpdateChildCommentReq) (*pb.UpdateChildCommentResp, error) {
	l := logic.NewUpdateChildCommentLogic(ctx, s.svcCtx)
	return l.UpdateChildComment(in)
}

func (s *CommentServer) DelChildComment(ctx context.Context, in *pb.DelChildCommentReq) (*pb.DelChildCommentResp, error) {
	l := logic.NewDelChildCommentLogic(ctx, s.svcCtx)
	return l.DelChildComment(in)
}

func (s *CommentServer) GetChildCommentByPId(ctx context.Context, in *pb.GetChildCommentByPidReq) (*pb.GetChildCommentByPidResp, error) {
	l := logic.NewGetChildCommentByPIdLogic(ctx, s.svcCtx)
	return l.GetChildCommentByPId(in)
}

func (s *CommentServer) SearchChildComment(ctx context.Context, in *pb.SearchChildCommentReq) (*pb.SearchChildCommentResp, error) {
	l := logic.NewSearchChildCommentLogic(ctx, s.svcCtx)
	return l.SearchChildComment(in)
}

// -----------------------comment-----------------------
func (s *CommentServer) AddComment(ctx context.Context, in *pb.AddCommentReq) (*pb.AddCommentResp, error) {
	l := logic.NewAddCommentLogic(ctx, s.svcCtx)
	return l.AddComment(in)
}

func (s *CommentServer) UpdateComment(ctx context.Context, in *pb.UpdateCommentReq) (*pb.UpdateCommentResp, error) {
	l := logic.NewUpdateCommentLogic(ctx, s.svcCtx)
	return l.UpdateComment(in)
}

func (s *CommentServer) DelComment(ctx context.Context, in *pb.DelCommentReq) (*pb.DelCommentResp, error) {
	l := logic.NewDelCommentLogic(ctx, s.svcCtx)
	return l.DelComment(in)
}

func (s *CommentServer) GetCommentByPid(ctx context.Context, in *pb.GetCommentByPidReq) (*pb.GetCommentByPidResp, error) {
	l := logic.NewGetCommentByPidLogic(ctx, s.svcCtx)
	return l.GetCommentByPid(in)
}

func (s *CommentServer) SearchComment(ctx context.Context, in *pb.SearchCommentReq) (*pb.SearchCommentResp, error) {
	l := logic.NewSearchCommentLogic(ctx, s.svcCtx)
	return l.SearchComment(in)
}
